#!/bin/bash

source set_paths.sh

vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/1024_ocean_tex.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/1024_island_tex.tif
vpbmaster --patch build_master.source -d Custom/airport_xgen/tif/1024_island_dem.tif

# vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/00_low_res.tif

vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/001_s_rwy_centerline.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/002_n_rwy_centerline.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/003_s_rwy_centerline.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/004_n_rwy_centerline.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/005_s_rwy_centerline.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/006_n_rwy_centerline.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/007_s_rwy_centerline.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/008_n_rwy_centerline.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/009_s_rwy_centerline.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/010_n_rwy_centerline.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/011_s_rwy_centerline.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/012_n_rwy_centerline.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/013_s_rwy_centerline.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/014_n_rwy_centerline.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/015_s_rwy_centerline.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/016_n_rwy_centerline.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/017_s_rwy_centerline.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/018_n_rwy_centerline.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/019_s_rwy_taxiway.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/020_n_rwy_taxiway.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/021_s_rwy_touchdown_1b.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/022_n_rwy_touchdown_1b.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/023_s_rwy_centerline.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/024_n_rwy_centerline.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/025_s_rwy_centerline.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/026_n_rwy_centerline.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/027_s_rwy_touchdown_1a.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/028_n_rwy_touchdown_1a.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/029_s_rwy_centerline.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/030_n_rwy_centerline.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/031_s_rwy_touchdown_2b.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/032_n_rwy_touchdown_2b.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/033_s_rwy_centerline.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/034_n_rwy_centerline.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/035_s_rwy_centerline.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/036_n_rwy_centerline.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/037_s_rwy_touchdown_2a.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/038_n_rwy_touchdown_2a.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/039_s_rwy_centerline.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/040_n_rwy_centerline.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/041_s_rwy_aiming.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/042_n_rwy_aiming.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/043_s_rwy_centerline.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/044_n_rwy_centerline.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/045_s_rwy_centerline.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/046_n_rwy_centerline.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/047_s_rwy_touchdown_3a.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/048_n_rwy_touchdown_3a.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/049_s_rwy_centerline.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/050_n_rwy_centerline.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/051_s_rwy_threshold_36.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/052_n_rwy_threshold_18.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/053_twy_holding.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/054_twy_holding.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/055_twy_holding.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/056_twy_holding.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/057_twy_latt.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/058_twy_latt.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/059_twy_latt.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/060_twy_latt.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/061_s_twy_turn.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/062_n_twy_turn.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/063_twy_crossing_L.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/064_twy_crossing_L.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/065_twy_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/066_twy_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/067_twy_crossing_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/068_twy_crossing_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/069_twy_crossing_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/070_twy_crossing_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/071_twy_crossing_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/072_twy_crossing_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/073_twy_crossing_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/074_twy_crossing_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/075_twy_crossing_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/076_twy_crossing_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/077_twy_crossing_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/078_twy_crossing_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/079_twy_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/080_twy_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/081_twy_crossing_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/082_twy_crossing_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/083_twy_long.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/084_twy_long.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/085_twy_long.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/086_twy_long.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/087_twy_long.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/088_twy_long.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/089_twy_crossing_R.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/090_twy_crossing_R.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/091_twy_latt.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/092_twy_latt.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/093_twy_latt.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/094_twy_latt.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/095_twy_long.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/096_twy_long.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/097_twy_long.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/098_twy_long.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/099_twy_long.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/100_twy_long.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/101_twy_long.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/102_twy_long.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/103_twy_long.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/104_twy_long.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/105_twy_long.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/106_twy_long.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/107_twy_long.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/108_twy_long.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/109_twy_long.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/110_twy_long.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/111_twy_long.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/112_twy_long.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/113_twy_long.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/114_twy_long.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/115_twy_long.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/116_twy_long.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/117_helipad.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/118_helipad.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/119_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/120_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/121_apron_long.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/122_apron_long.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/123_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/124_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/125_apron_latt.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/126_apron_latt.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/127_apron_crossing.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/128_apron_crossing.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/129_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/130_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/131_apron_latt.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/132_apron_latt.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/133_apron_crossing.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/134_apron_crossing.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/135_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/136_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/137_apron_latt.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/138_apron_latt.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/139_apron_crossing.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/140_apron_crossing.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/141_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/142_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/143_apron_latt.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/144_apron_latt.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/145_apron_crossing.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/146_apron_crossing.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/147_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/148_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/149_apron_latt.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/150_apron_latt.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/151_apron_crossing.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/152_apron_crossing.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/153_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/154_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/155_apron_latt.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/156_apron_latt.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/157_apron_crossing.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/158_apron_crossing.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/159_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/160_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/161_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/162_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/163_apron_long.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/164_apron_long.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/165_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/166_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/167_apron_latt.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/168_apron_latt.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/169_s_apron_turn.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/170_n_apron_turn.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/171_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/172_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/173_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/174_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/175_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/176_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/177_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/178_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/179_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/180_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/181_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/182_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/183_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/184_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/185_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/186_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/187_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/188_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/189_apron.tif
vpbmaster --patch build_master.source -t Custom/airport_xgen/tif/190_apron.tif

notify-send "Patching (XGEN) Generic" "Finished."
